version: '3'
services:
  redis:
    image: redis
    ports:
      - '6379:6379'
    env_file:
      - /configs/.env

  db:
    restart: always
    image: postgres:latest
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    env_file:
      - /configs/.env
    ports:
      - 5432:5432

  admin:
    build:
      context: ./bot1
      dockerfile: admin_bot/Dockerfile
    depends_on:
      - redis
      - db
    env_file:
      - /configs/.env

  user:
    build:
      dockerfile: user/Dockerfile
    depends_on:
      - redis
      - db
    env_file:
      - /configs/.env


