version: '3'
services:
  redis:
    image: redis
    ports:
      - '6379:6379'
    networks:
      - mynetwork

  telegrambot-bot1:
    build:
      context: ./bot1
      dockerfile: Dockerfile.bot1
    depends_on:
      - redis
    networks:
      - mynetwork

  telegrambot-bot2:
    build:
      context: ./bot2
      dockerfile: Dockerfile.bot2
    depends_on:
      - redis
    networks:
      - mynetwork

networks:
  mynetwork:
